name: Release metrics adapter chart
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'This is a pre-release'
        required: false
        default: false
        type: boolean

jobs:
  # Sometimes chart-releaser might fetch an outdated index.yaml from gh-pages, causing a WAW hazard on the repo
  # This job checks the remote file is up to date with the local one on release
  validate-gh-pages-index:
    runs-on: ubuntu-latest
    env:
      CHART_NAME: newrelic-k8s-metrics-adapter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Download remote index file and check equality
        run: |
          curl -vsSL https://newrelic.github.io/$CHART_NAME/index.yaml > index.yaml.remote
          LOCAL="$(md5sum < index.yaml)"
          REMOTE="$(md5sum < index.yaml.remote)"
          echo "$LOCAL" = "$REMOTE"
          test "$LOCAL" = "$REMOTE"

  release:
    runs-on: ubuntu-latest
    needs: [ validate-gh-pages-index ]
    env:
      CHART_NAME: newrelic-k8s-metrics-adapter
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # In case it is a pre-release we add `-pre` so it is not considered stable, so we can prerelease and test it properly.
      - name: Change chart's version if this run is a pre-release
        if: ${{ github.event.input.prerelease }}
        run: |
          sed -i 's|^version: \(.*\)|version: \1-pre|' ./charts/$CHART_NAME/Chart.yaml
          sed -i 's|^appVersion: \(.*\)|appVersion: \1-pre|' ./charts/$CHART_NAME/Chart.yaml

      # Chart releaser is going to look for changes with the latest tag of this chart. This commit is going to be the same
      # as when we pre-released so chart releaser is not going to see any changed in the helm chart and it is not going to
      # release any chart. To force chart release to see the remaining history of this repo, we are removing the tag that
      # could exist in case of a previous pre-release. We are not going to fail in case we are not able to remove it as it
      # could not exist.
      - name: Change chart's version if this run is a pre-release
        if: ${{ ! github.event.input.prerelease }}
        run: |
          CHART_VERSION=$(grep -E "^appVersion: " ./charts/$CHART_NAME/Chart.yaml | sed -e 's|^appVersion: \(.*\)|appVersion: \1|')
          CHART_TAG_PRE="${CHART_NAME}-${CHART_VERSION}-pre"
          git tag --delete CHART_TAG_PRE || true

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release workload charts
        uses: helm/chart-releaser-action@v1.3.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
